### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by Barkells** [Qendolin/better-clouds#110]
1.21 support pleaseeeeee

**Comment by medina1337** [comment]
waiting for it too :c

**Comment by Qendolin** [comment]
I'll do it but so far I haven't had time. Remind me in two weeks.

**Comment by medina1337** [comment]
No worries. I'm so used to better clouds that it feels off to play without. Have a great week! <3

**Comment by Barkells** [comment]
weekly reminder!

**Comment by Qendolin** [comment]
Thanks, I'll probably look into it on Wednesday

**Comment by Qendolin** [comment]
It's almost ready, just facing an issue with iris which is preventing me from building the jar.

**Comment by ByteSix** [comment]
> It's almost ready, just facing an issue with iris which is preventing me from building the jar.

Lol what are the ods that you posted this literally just now as I'm looking into a 1.21 update on the github.

**Comment by Qendolin** [comment]
Anyone know's a fix for this?
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':remapJar'.
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: duplicate field net/irisshaders/iris/mixin/vertices/MixinBufferBuilder/vertexCount;;I in inputs
Caused by: java.lang.RuntimeException: duplicate field net/irisshaders/iris/mixin/vertices/MixinBufferBuilder/vertexCount;;I in inputs
	at net.fabricmc.tinyremapper.TinyRemapper$3.visitField(TinyRemapper.java:632)
	at org.objectweb.asm.ClassReader.readField(ClassReader.java:1138)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:740)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:642)
	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:71)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:553)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:549)
	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:549)
	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:71)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:521)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:517)
```

**Comment by Qendolin** [comment]
No, the error is specific to Iris. Something with them using mojmap instead of yarn.

**Comment by geeatsu** [comment]
Hmm I have no idea then. My only past experiences with programming/compiling was trying to update better clouds to 1.21 by myself.

**Comment by geeatsu** [comment]
![image](https://github.com/Qendolin/better-clouds/assets/100881879/d52a65dc-b200-41a2-b69a-ce3626d8c8fb)
prob not related but I found this 
![image](https://github.com/Qendolin/better-clouds/assets/100881879/c485eb46-5633-4943-808a-eba1c7d29bfc)

**Comment by OzzyOsb2000** [comment]
> Anyone knows a fix for this?
> 
> ```
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':remapJar'.
> Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: duplicate field net/irisshaders/iris/mixin/vertices/MixinBufferBuilder/vertexCount;;I in inputs
> Caused by: java.lang.RuntimeException: duplicate field net/irisshaders/iris/mixin/vertices/MixinBufferBuilder/vertexCount;;I in inputs
> 	at net.fabricmc.tinyremapper.TinyRemapper$3.visitField(TinyRemapper.java:632)
> 	at org.objectweb.asm.ClassReader.readField(ClassReader.java:1138)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:740)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
> 	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:642)
> 	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:71)
> 	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:553)
> 	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:549)
> 	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:549)
> 	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:71)
> 	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:521)
> 	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:517)
> ```

Any update ? You can fix the problem?

**Comment by Qendolin** [comment]
Its done:
https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
I have backported the changes to 1.20.6, 1.20.4 ad 1.20.1

**Comment by geeatsu** [comment]
Legend
