### ISSUE TITLE
Unable to start game (Probably due to mod incompatiblity)

### ISSUE THREAD

**Issue by zqilz** [Qendolin/better-clouds#120]
## Description
> Unable to start game (Probably due to mod incompatibility)

### System Environment
- GPU: NVIDIA GeForce GTX 1650
- Mod Version: 1.70+1.21-b
- OS: Windows 11

*Optional:*
- Shader Pack: 
- Other Mods: Appleskin, Architectury API, Auto Clicker, Balm, Better F3, Cicada, Chunks Fade In, Client Tweaks, Cloth Config API, Clumps, Collective, Continuity, Controlling, Cull Leaves, Do a Barrel Roll, Dynamic FPS, EMI, Eating Animation, Emoji Type, Enhanced Block Entities, Entity Culling, Fabric Language Kotlin, Fast Chest, FerritCore, Freecam, Fzzy Config, Immediately Fast, Indium, Iris Shaders, Krypton, Lighty, Lithium, Mod Menu, Model Gap Fix, Modern Fix, Mouse Tweaks, Not Enough Animations, Nvidium, Particle Core, Presence Footsteps, Reese's Sodium Options, REI, Searchables, Shulker Box Tooltips, Sodium, Sodium Extra, Sound Physics Remastered, Stack Refill, Text Placeholder API, Video Tape, Visuality, Xaero's Minimap, YetAnotherConfigLib, EMF, ETF

### Game Log / Crash Report
[latest.log](https://github.com/user-attachments/files/16040209/latest.log)

Fabric Loader's Log: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'betterclouds'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'betterclouds'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 5 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'betterclouds'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.qendolin.betterclouds.PreLaunchHandler failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [yacl-fabric.mixins.json:ContainerEventHandlerMixin from mod yet_another_config_lib_v3] from phase [DEFAULT] in config [yacl-fabric.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: yacl-fabric.mixins.json:ContainerEventHandlerMixin from mod yet_another_config_lib_v3 target net.minecraft.class_4069 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 23 more

**Comment by Qendolin** [comment]
I can't reproduce this issue. I have installed the exact same mods as were listed in the log file but everything works correctly. The only difference is that you are using the Feather launcher. Have you tried launching the game with just Better Clouds, Mod Menu, Yet Another Config Lib and Fabric Api? Can you try using another launcher?

**Comment by zqilz** [comment]
Well, I did some more testing and it seems like the problem lies on YACL's incompatibility with feather.
No matter what I did, YACL would either completely shut itself off, not even registering as a mod, or stops the client from launching. Eitherway, thank you for your research; I've switched over to modrinth (it wasn't updated to 1.21 at the time) and it works just fine.
