### ISSUE TITLE
Incompatible with AutoHarvest

### ISSUE THREAD

**Issue by SAJewers** [Qendolin/better-clouds#3]
Attempting to launch with both Better Clouds and [AutoHarvest](https://www.curseforge.com/minecraft/mc-mods/autoharvest) produces the following error: 

java.lang.RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods autoharvest and betterclouds
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:85)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Qendolin** [comment]
Will be fixed with https://github.com/Qendolin/better-clouds/pull/1. I've also opened an [issue](https://github.com/flier268/AutoHarvestMod/issues/17) for autoharvest.

**Comment by Qendolin** [comment]
Fixed https://modrinth.com/mod/better-clouds/version/f4jg6EtK
